"""add user status

Revision ID: f8992f42c998
Revises: bb602092201d
Create Date: 2025-02-24 17:05:34.261562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f8992f42c998"
down_revision: Union[str, None] = "bb602092201d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("status", sa.String(length=20), nullable=True))
    user = sa.table("user", sa.column("id", sa.Integer), sa.column("status", sa.String))
    op.execute(user.update().values(status="offline"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "status")
    # ### end Alembic commands ###
